### ISSUE TITLE
--xml argument doesn't produce valid XML.

### ISSUE THREAD

**Issue by bear454** [SUSE/Enceladus#118]
Instead of outputting XML, the JSON data is wrapped in an XML tag.

```
# /usr/sbin/azuremetadata --tag --xml --device /dev/sda
<document>{
   "billingTag" : "2ab96a9e-13b8-41b5-be70-4c3b90e5dd35"
}</document>
```

I'd expect output more like:
```
<document>
    <billingTag>2ab96a9e-13b8-41b5-be70-4c3b90e5dd35</billingTag>
</document>
```

**Comment by schaefi** [comment]
Hmm, yes that's weird. I'll fix it

**Comment by schaefi** [comment]
I closed the PR because I think we should not change it. The change causes other changed on azureInstanceVerify as well as requires changes on the SMT Servers in Azure. I think this is not worth the potential trouble. However I kept the branch open
