### ISSUE TITLE
pint should have a pretty print option

### ISSUE THREAD

**Issue by rjschwei** [SUSE/Enceladus#64]
We should have a pretty print option that nicely indents xml and json output rather than producing things on one line.

**Comment by bear454** [comment]
JSON and XML parsers should have no problem with the extra whitespace, so how about we do this as the default instead of adding an option?

**Comment by rjschwei** [comment]
On 11/20/2015 11:28 AM, James Mason wrote:

> JSON and XML parsers should have no problem with the extra whitespace, so how about we do this as the default instead of adding an option?

Works for me.

## 

Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo
