### ISSUE TITLE
improve code effciciency for ec2utils region determination

### ISSUE THREAD

**Issue by rjschwei** [SUSE/Enceladus#82]
As of version 1.3 boto3 provides and API to get the connected regions:

boto3.session.Session(
    aws_access_key_id=access_key,
    aws_secret_access_key=secret_key
).get_available_regions('ec2')

Currently in ec2utilsutils.py:get_regions the disconnected regions are hard coded which requires a code change if a new disconnected region is added to AWS.

**Comment by rjschwei** [comment]
Implementation of this requires dependency on boto3 >= 1.3 which has some packaging implications for SLES and openSUSE

**Comment by rjschwei** [comment]
http://boto3.readthedocs.org/en/latest/reference/core/session.html?highlight=region#boto3.session.Session.get_available_regions

**Comment by bear454** [comment]
https://software.opensuse.org/package/python3-boto3 is already on 1.3; we need to get https://software.opensuse.org/package/python-boto3 caught up.
