### ISSUE TITLE
Endless ssh attempts in ec2uploadimg

### ISSUE THREAD

**Issue by nbayle** [SUSE/Enceladus#97]
(Posted this is suse-users, was told to post this here as a possible bug)

```
ec2uploadimg -a prod -m x86_64 -n akm_4.0_sles11_sp4.x86_64-1.0.86 -d akm_4.0_sles11_sp4.x86_64-1.0.86 -r us-east-1 akm_4.0_sles11_sp4.x86_64-1.0.86.ec2.tar.gz --verbose --ssh-timeout 5
Using EC2 region:  us-east-1

Waiting for instance:  i-77612d8f
.  .  . 
Waiting for volume creation:  vol-7adbbafb
. 
Wait for volume attachment
. 
Waiting for volume creation:  vol-dfdabb5e
. 
Wait for volume attachment
. 
Waiting to obtain instance IP address
. 
Attempt ssh connection
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ^C
Traceback (most recent call last):
  File "/usr/local/bin/ec2uploadimg", line 4, in <module>
    __import__('pkg_resources').run_script('ec2uploadimg==1.1.3', 'ec2uploadimg')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ec2uploadimg-1.1.3-py2.7.egg/EGG-INFO/scripts/ec2uploadimg", line 430, in <module>

  File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 838, in create_image
  File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 946, in create_snapshot
  File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 277, in _create_image_root_volume
  File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 525, in _establish_ssh_connection
KeyboardInterrupt
```

There was definitely an hour of waiting in there, so I assume the ssh attempts will go on forever.

**Comment by rjschwei** [comment]
On 09/22/2016 10:45 AM, Nicholas wrote:

> (Posted this is suse-users, was told to post this here as a possible bug)
> 
> ```
> ec2uploadimg -a prod -m x86_64 -n akm_4.0_sles11_sp4.x86_64-1.0.86 -d akm_4.0_sles11_sp4.x86_64-1.0.86 -r us-east-1 akm_4.0_sles11_sp4.x86_64-1.0.86.ec2.tar.gz --verbose --ssh-timeout 5
> Using EC2 region:  us-east-1
> 
> Waiting for instance:  i-77612d8f
> .  .  . 
> Waiting for volume creation:  vol-7adbbafb
> . 
> Wait for volume attachment
> . 
> Waiting for volume creation:  vol-dfdabb5e
> . 
> Wait for volume attachment
> . 
> Waiting to obtain instance IP address
> . 
> Attempt ssh connection
> .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ^C
> Traceback (most recent call last):
>   File "/usr/local/bin/ec2uploadimg", line 4, in <module>
>     __import__('pkg_resources').run_script('ec2uploadimg==1.1.3', 'ec2uploadimg')
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/local/lib/python2.7/dist-packages/ec2uploadimg-1.1.3-py2.7.egg/EGG-INFO/scripts/ec2uploadimg", line 430, in <module>
> 
>   File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 838, in create_image
>   File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 946, in create_snapshot
>   File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 277, in _create_image_root_volume
>   File "build/bdist.linux-x86_64/egg/ec2utils/ec2uploadimg.py", line 525, in _establish_ssh_connection
> KeyboardInterrupt
> ```
> 
> There was definitely an hour of waiting in there, so I assume the ssh attempts will go on forever.

Yes they will.

Is the instance i-77612d8f in EC2 actually running?
Can you login to the instance with the key you provided in your
~/.ec2utils config file?
Does the default security group configured for this account allow ssh
access?
Does then network from which you are uploading allow ssh egress to the
external IP of the EC2 instance?

It is most likely that your ssh traffic is getting dropped somewhere.

**Comment by nbayle** [comment]
Ha! Yes... the security group was blocking. But apparently I still can't connect because it won't boot. 

![z](https://cloud.githubusercontent.com/assets/8433050/18853526/75c1e54a-83fa-11e6-9bc8-93117d50eaeb.jpg)

Should I head back to suse-users to debug this?

**Comment by rjschwei** [comment]
This could be a multitude of things:
1.) The <type> definition of your image build is not correct
2.) Kernel and virtualization type do not match up, i.e. you uploaded with -V hvm but used the -ec2 kernel in the image build
3.) You have a PV image but picked an aki- that does not match 32 vs 64 bit, aki numbers are easily mistyped

And yes this is not an issue with the uploader.
